name: flutter_quitanda
description: App de Quitanda.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  add_to_cart_animation: 0.0.7
  animated_text_kit: ^4.2.2
  badges: ^2.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  mask_text_input_formatter: ^2.3.0
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/frutas/
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true    
